{{- if and .Values.resend.webhookSecret (not .Values.resend.existingSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "resend-exporter.fullname" . }}
  labels:
    {{- include "resend-exporter.labels" . | nindent 4 }}
type: Opaque
stringData:
  webhook-secret: {{ .Values.resend.webhookSecret | quote }}
{{- end }}
